spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.50.17:3306/lhs
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true